{"uuid": "2e903c58-63e8-4921-8b27-f99ceabde121", "historyId": "0d6f14f65490724d47c8713d3b260af0", "name": "Incorrect password cannot log in", "labels": [{"value": "normal", "name": "severity"}, {"value": "OneDrive upload and verification", "name": "feature"}, {"value": "behave", "name": "framework"}, {"value": "cpython3", "name": "language"}], "steps": [{"stop": 1593794387042, "start": 1593794380573, "name": "Given the User is navigates to One Drive page", "status": "passed"}, {"statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=83.0.4103.97)\n\n", "trace": "  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/one_drive_steps.py\", line 40, in select_locale\n    locale_btn = driver.find_element_by_id('dynamicmarketredirect-dialog-submit')\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py\", line 360, in find_element_by_id\n    return self.find_element(by=By.ID, value=id_)\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "stop": 1593794387055, "start": 1593794387043, "name": "And selects Locale", "status": "broken"}, {"stop": 1593794387083, "start": 1593794387083, "name": "When the User clicks Sign In", "status": "skipped"}, {"stop": 1593794387084, "start": 1593794387084, "name": "And the User enters email in E-mail field", "status": "skipped"}, {"stop": 1593794387084, "start": 1593794387084, "name": "And submits email", "status": "skipped"}, {"stop": 1593794387084, "start": 1593794387084, "name": "And the User enters incorrect password in Password field", "status": "skipped"}, {"stop": 1593794387084, "start": 1593794387084, "name": "And submits password", "status": "skipped"}, {"stop": 1593794387084, "start": 1593794387084, "name": "Then incorrect password error message is shown", "status": "skipped"}], "stop": 1593794387084, "start": 1593794378920, "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=83.0.4103.97)\n\n", "trace": "  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/one_drive_steps.py\", line 40, in select_locale\n    locale_btn = driver.find_element_by_id('dynamicmarketredirect-dialog-submit')\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py\", line 360, in find_element_by_id\n    return self.find_element(by=By.ID, value=id_)\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/scarlet/Projects/PyEnvs/Automation/QAEnv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "status": "broken"}